import React from 'react'

const Dummy = [
    {
        "root": {
            "id": "toplevel",
            "relevance": 1.0,
            "fields": {
                "totalCount": 162
            },
            "coverage": {
                "coverage": 100,
                "documents": 5363,
                "full": true,
                "nodes": 1,
                "results": 1,
                "resultsFull": 1
            },
            "children": [
                {
                    "id": "id:bqcompany2:bqcompany2::330098815",
                    "relevance": 8.206787861139798,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::330098815",
                        "bq_company_name": "HYUNDAI MOTOR AMERICA",
                        "bq_year_founded": "1985",
                        "bq_industry_name": "Motor Vehicle & Motor Vehicle Parts & Supplies",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Multi-entity U.S. organization",
                        "bq_sector_name": "Wholesale Trade",
                        "bq_naics_description": "New Car Dealers",
                        "bq_company_ein": "330098815",
                        "bq_naics_code": "441110",
                        "bq_organization_jurisdiction_code": "US_CA",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Corporation",
                        "bq_naics_sector_code": "42",
                        "bq_naics_sector_name": "Wholesale Trade",
                        "bq_revenue_mr": 1026415387.0,
                        "bq_company_address1_line_1": "10550 Talbert Ave",
                        "bq_company_address1_city": "Fountain Valley",
                        "bq_company_address1_state": "CA",
                        "bq_company_address1_state_name": "California",
                        "bq_company_address1_county_fips": "06059",
                        "bq_company_address1_county_name": "Orange County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "92708",
                        "bq_company_address1_zip9": "92708-6031",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "Match-Mailable",
                        "bq_company_address1_rdi": "Commercial",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "31080",
                        "bq_company_address1_cbsa_name": "Los Angeles-Long Beach-Anaheim, CA",
                        "bq_company_address1_cbsa_type": "Metro",
                        "bq_company_address1_location": {
                            "lat": 33.70165,
                            "lng": -117.94501
                        }
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::953141669",
                    "relevance": 7.84760076366169,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::953141669",
                        "bq_company_name": "TOYOTA MOTOR CORP",
                        "bq_industry_name": "Motor Vehicle Manufacturing",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Single-entity organization",
                        "bq_sector_name": "Manufacturing",
                        "bq_naics_description": "Automobile Manufacturing; Light Truck and Utility Vehicle Manufacturing; Heavy Duty Truck Manufacturing",
                        "bq_company_ein": "953141669",
                        "bq_naics_code": "336111; 336112; 336120",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Corporation",
                        "bq_naics_sector_code": "31-33",
                        "bq_naics_sector_name": "Manufacturing",
                        "bq_revenue_mr": 266690397301.0,
                        "bq_company_address1_line_1": "6565 Headquarters Dr",
                        "bq_company_address1_city": "Plano",
                        "bq_company_address1_state": "TX",
                        "bq_company_address1_state_name": "Texas",
                        "bq_company_address1_county_fips": "48085",
                        "bq_company_address1_county_name": "Collin County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "75024",
                        "bq_company_address1_zip9": "75024-5965",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "Match-Mailable",
                        "bq_company_address1_rdi": "Commercial",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "19100",
                        "bq_company_address1_cbsa_name": "Dallas-Fort Worth-Arlington, TX",
                        "bq_company_address1_cbsa_type": "Metro",
                        "bq_company_address1_location": {
                            "lat": 33.08024,
                            "lng": -96.84543
                        },
                        "bq_public_indicator": "true",
                        "bq_revenue_growth_yoy_mr": "0.003309349550949525"
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::380549190",
                    "relevance": 7.84760076366169,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::380549190",
                        "bq_company_name": "FORD MOTOR CO",
                        "bq_year_founded": "1997",
                        "bq_industry_name": "Motor Vehicle Manufacturing",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Multi-entity U.S. organization",
                        "bq_sector_name": "Manufacturing",
                        "bq_naics_description": "New Car Dealers",
                        "bq_company_ein": "380549190",
                        "bq_naics_code": "441110",
                        "bq_organization_jurisdiction_code": "US_MI",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Corporation",
                        "bq_naics_sector_code": "31-33",
                        "bq_naics_sector_name": "Manufacturing",
                        "bq_revenue_mr": 158057000000.0,
                        "bq_company_address1_line_1": "Tax Department 1 American Road Ford Whq Room 612",
                        "bq_company_address1_city": "Dearborn",
                        "bq_company_address1_state": "MI",
                        "bq_company_address1_state_name": "Michigan",
                        "bq_company_address1_county_fips": "26163",
                        "bq_company_address1_county_name": "Wayne County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "48126",
                        "bq_company_address1_zip9": "48126",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "No Match",
                        "bq_company_address1_rdi": "Unknown",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "19820",
                        "bq_company_address1_cbsa_name": "Detroit-Warren-Dearborn, MI",
                        "bq_company_address1_cbsa_type": "Metro",
                        "bq_company_address1_location": {
                            "lat": 42.33212,
                            "lng": -83.18309
                        },
                        "bq_public_indicator": "true"
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::270383222",
                    "relevance": 7.84760076366169,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::270383222",
                        "bq_company_name": "GENERAL MOTORS CO",
                        "bq_industry_name": "Motor Vehicle Manufacturing",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Single-entity organization",
                        "bq_sector_name": "Manufacturing",
                        "bq_naics_description": "Automobile Manufacturing; Light Truck and Utility Vehicle Manufacturing; Heavy Duty Truck Manufacturing",
                        "bq_company_ein": "270383222",
                        "bq_naics_code": "336111; 336112; 336120",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Corporation",
                        "bq_naics_sector_code": "31-33",
                        "bq_naics_sector_name": "Manufacturing",
                        "bq_revenue_mr": 156735000000.0,
                        "bq_company_address1_line_1": "300 Renaissance Ctr",
                        "bq_company_address1_city": "Detroit",
                        "bq_company_address1_state": "MI",
                        "bq_company_address1_state_name": "Michigan",
                        "bq_company_address1_county_fips": "26163",
                        "bq_company_address1_county_name": "Wayne County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "48243",
                        "bq_company_address1_zip9": "48243-1402",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "Yes",
                        "bq_company_address1_summary": "Match-Mailable",
                        "bq_company_address1_rdi": "Commercial",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_location": {
                            "lat": 42.32997,
                            "lng": -83.03991
                        },
                        "bq_public_indicator": "true"
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::952041006",
                    "relevance": 7.431969081853248,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::952041006",
                        "bq_company_name": "HONDA MOTOR CO LTD",
                        "bq_industry_name": "Motor Vehicle Manufacturing",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Single-entity organization",
                        "bq_sector_name": "Manufacturing",
                        "bq_naics_description": "Automobile Manufacturing; Light Truck and Utility Vehicle Manufacturing; Heavy Duty Truck Manufacturing",
                        "bq_company_ein": "952041006",
                        "bq_naics_code": "336111; 336112; 336120",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Corporation",
                        "bq_naics_sector_code": "31-33",
                        "bq_naics_sector_name": "Manufacturing",
                        "bq_revenue_mr": 122932331334.0,
                        "bq_company_address1_line_1": "1919 Torrance Blvd",
                        "bq_company_address1_city": "Torrance",
                        "bq_company_address1_state": "CA",
                        "bq_company_address1_state_name": "California",
                        "bq_company_address1_county_fips": "06037",
                        "bq_company_address1_county_name": "Los Angeles County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "90501",
                        "bq_company_address1_zip9": "90501-2722",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "Match-Mailable",
                        "bq_company_address1_rdi": "Commercial",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "31080",
                        "bq_company_address1_cbsa_name": "Los Angeles-Long Beach-Anaheim, CA",
                        "bq_company_address1_cbsa_type": "Metro",
                        "bq_company_address1_location": {
                            "lat": 33.83642,
                            "lng": -118.31611
                        },
                        "bq_public_indicator": "true",
                        "bq_revenue_growth_yoy_mr": "0.0024457253381353627"
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::630636444",
                    "relevance": 7.431969081853248,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::630636444",
                        "bq_company_name": "TIFFIN MOTOR HOMES, INC.",
                        "bq_year_founded": "1985",
                        "bq_industry_name": "Motor Vehicle Manufacturing",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Multi-entity U.S. organization",
                        "bq_sector_name": "Manufacturing",
                        "bq_naics_description": "Used Car Dealers",
                        "bq_company_ein": "630636444",
                        "bq_naics_code": "441120",
                        "bq_organization_jurisdiction_code": "US_DE",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Corporation",
                        "bq_naics_sector_code": "31-33",
                        "bq_naics_sector_name": "Manufacturing",
                        "bq_revenue_mr": 762196795.0,
                        "bq_company_address1_line_1": "PO Box 387",
                        "bq_company_address1_city": "Red Bay",
                        "bq_company_address1_state": "AL",
                        "bq_company_address1_state_name": "Alabama",
                        "bq_company_address1_county_fips": "01059",
                        "bq_company_address1_county_name": "Franklin County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "35582",
                        "bq_company_address1_zip9": "35582-0387",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "Match-Mailable",
                        "bq_company_address1_rdi": "Residential",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "99999",
                        "bq_company_address1_location": {
                            "lat": 34.4443,
                            "lng": -88.14644
                        }
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::221824424",
                    "relevance": 7.188016905761581,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::221824424",
                        "bq_company_name": "KAWASAKI MOTORS CORP., U.S.A.",
                        "bq_year_founded": "1967",
                        "bq_industry_name": "Motor Vehicle & Motor Vehicle Parts & Supplies",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Multi-entity U.S. organization",
                        "bq_sector_name": "Wholesale Trade",
                        "bq_naics_description": "Used Car Dealers",
                        "bq_company_ein": "221824424",
                        "bq_naics_code": "441120",
                        "bq_organization_jurisdiction_code": "US_DE",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Corporation",
                        "bq_naics_sector_code": "42",
                        "bq_naics_sector_name": "Wholesale Trade",
                        "bq_revenue_mr": 1106412706.0,
                        "bq_company_address1_line_1": "26972 Burbank",
                        "bq_company_address1_city": "Foothill Ranch",
                        "bq_company_address1_state": "CA",
                        "bq_company_address1_state_name": "California",
                        "bq_company_address1_county_fips": "06059",
                        "bq_company_address1_county_name": "Orange County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "92610",
                        "bq_company_address1_zip9": "92610-2506",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "Match-Mailable",
                        "bq_company_address1_rdi": "Commercial",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "31080",
                        "bq_company_address1_cbsa_name": "Los Angeles-Long Beach-Anaheim, CA",
                        "bq_company_address1_cbsa_type": "Metro",
                        "bq_company_address1_location": {
                            "lat": 33.67881,
                            "lng": -117.66001
                        }
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::371426698",
                    "relevance": 7.100035172950144,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::371426698",
                        "bq_company_name": "HYUNDAI MOTOR MANUFACTURING ALABAMA, LLC.",
                        "bq_year_founded": "2002",
                        "bq_industry_name": "Motor Vehicle Manufacturing",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Multi-entity U.S. organization",
                        "bq_sector_name": "Manufacturing",
                        "bq_naics_description": "New Car Dealers",
                        "bq_company_ein": "371426698",
                        "bq_naics_code": "441110",
                        "bq_organization_jurisdiction_code": "US_DE",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Limited Liability Company",
                        "bq_naics_sector_code": "31-33",
                        "bq_naics_sector_name": "Manufacturing",
                        "bq_revenue_mr": 1918582289.0,
                        "bq_company_address1_line_1": "700 Hyundai Blvd",
                        "bq_company_address1_city": "Montgomery",
                        "bq_company_address1_state": "AL",
                        "bq_company_address1_state_name": "Alabama",
                        "bq_company_address1_county_fips": "01101",
                        "bq_company_address1_county_name": "Montgomery County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "36105",
                        "bq_company_address1_zip9": "36105-9622",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "Match-Mailable",
                        "bq_company_address1_rdi": "Commercial",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "33860",
                        "bq_company_address1_cbsa_name": "Montgomery, AL",
                        "bq_company_address1_cbsa_type": "Metro",
                        "bq_company_address1_location": {
                            "lat": 32.27773,
                            "lng": -86.32986
                        }
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::111362020",
                    "relevance": 7.047641971420283,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::111362020",
                        "bq_company_name": "STANDARD MOTOR PRODUCTS INC",
                        "bq_industry_name": "Motor Vehicle Parts Manufacturing",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Single-entity organization",
                        "bq_sector_name": "Manufacturing",
                        "bq_naics_description": "Motor Vehicle Gasoline Engine and Engine Parts Manufacturing; Motor Vehicle Electrical and Electronic Equipment Manufacturing; Motor Vehicle Steering and Suspension Components (except Spring) Manufacturing; Motor Vehicle Brake System Manufacturing; Motor Vehicle Transmission and Power Train Parts Manufacturing; Motor Vehicle Seating and Interior Trim Manufacturing; Motor Vehicle Metal Stamping; Other Motor Vehicle Parts Manufacturing",
                        "bq_company_ein": "111362020",
                        "bq_naics_code": "336310; 336320; 336330; 336340; 336350; 336360; 336370; 336390",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Corporation",
                        "bq_naics_sector_code": "31-33",
                        "bq_naics_sector_name": "Manufacturing",
                        "bq_revenue_mr": 1371815000.0,
                        "bq_company_address1_line_1": "3718 Northern Blvd",
                        "bq_company_address1_city": "Long Island City",
                        "bq_company_address1_state": "NY",
                        "bq_company_address1_state_name": "New York",
                        "bq_company_address1_county_fips": "36081",
                        "bq_company_address1_county_name": "Queens County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "11101",
                        "bq_company_address1_zip9": "11101-1631",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "Yes",
                        "bq_company_address1_summary": "Match-Mailable",
                        "bq_company_address1_rdi": "Commercial",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "35620",
                        "bq_company_address1_cbsa_name": "New York-Newark-Jersey City, NY-NJ-PA",
                        "bq_company_address1_cbsa_type": "Metro",
                        "bq_company_address1_location": {
                            "lat": 40.75305,
                            "lng": -73.92652
                        },
                        "bq_public_indicator": "true"
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::581712286",
                    "relevance": 7.047641971420283,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::581712286",
                        "bq_company_name": "YAMAHA MOTOR MANUFACTURING CORPORATION",
                        "bq_year_founded": "1986",
                        "bq_industry_name": "Motor Vehicle Parts Manufacturing",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Multi-entity U.S. organization",
                        "bq_sector_name": "Manufacturing",
                        "bq_naics_description": "All Other Miscellaneous Manufacturing",
                        "bq_company_ein": "581712286",
                        "bq_naics_code": "339999",
                        "bq_organization_jurisdiction_code": "US_GA",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Corporation",
                        "bq_naics_sector_code": "31-33",
                        "bq_naics_sector_name": "Manufacturing",
                        "bq_revenue_mr": 882255216.0,
                        "bq_company_address1_line_1": "1000 Georgia Hwy. 34 E",
                        "bq_company_address1_city": "Newnan",
                        "bq_company_address1_state": "GA",
                        "bq_company_address1_state_name": "Georgia",
                        "bq_company_address1_county_fips": "13077",
                        "bq_company_address1_county_name": "Coweta County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "30265",
                        "bq_company_address1_zip9": "30265",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "No Match",
                        "bq_company_address1_rdi": "Unknown",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "12060",
                        "bq_company_address1_cbsa_name": "Atlanta-Sandy Springs-Alpharetta, GA",
                        "bq_company_address1_cbsa_type": "Metro",
                        "bq_company_address1_location": {
                            "lat": 33.40132,
                            "lng": -84.71223
                        }
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::952668359",
                    "relevance": 6.466456012051818,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::952668359",
                        "bq_company_name": "MAZDA MOTOR OF AMERICA, INC., DBA MAZDA NORTH AMERICAN OPERATIONS",
                        "bq_industry_name": "Motor Vehicle & Motor Vehicle Parts & Supplies",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Single-entity organization",
                        "bq_sector_name": "Wholesale Trade",
                        "bq_naics_description": "Automobile and Other Motor Vehicle Merchant Wholesalers; Motor Vehicle Supplies and New Parts Merchant Wholesalers; Tire and Tube Merchant Wholesalers; Motor Vehicle Parts (Used) Merchant Wholesalers",
                        "bq_company_ein": "952668359",
                        "bq_naics_code": "423110; 423120; 423130; 423140",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Corporation",
                        "bq_naics_sector_code": "42",
                        "bq_naics_sector_name": "Wholesale Trade",
                        "bq_revenue_mr": 896266572.0,
                        "bq_company_address1_line_1": "200 Spectrum Center Dr Ste 100",
                        "bq_company_address1_city": "Irvine",
                        "bq_company_address1_state": "CA",
                        "bq_company_address1_state_name": "California",
                        "bq_company_address1_county_fips": "06059",
                        "bq_company_address1_county_name": "Orange County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "92618",
                        "bq_company_address1_zip9": "92618-5004",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "Match-Mailable",
                        "bq_company_address1_rdi": "Commercial",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "31080",
                        "bq_company_address1_cbsa_name": "Los Angeles-Long Beach-Anaheim, CA",
                        "bq_company_address1_cbsa_type": "Metro",
                        "bq_company_address1_location": {
                            "lat": 33.6534,
                            "lng": -117.74484
                        }
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::560754594",
                    "relevance": 4.494479481310197,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::560754594",
                        "bq_company_name": "AMERICAN TIRE DISTRIBUTORS, INC.",
                        "bq_year_founded": "1998",
                        "bq_industry_name": "Motor Vehicle & Motor Vehicle Parts & Supplies",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Multi-entity U.S. organization",
                        "bq_sector_name": "Wholesale Trade",
                        "bq_naics_description": "Tire Dealers",
                        "bq_company_ein": "560754594",
                        "bq_naics_code": "441320",
                        "bq_organization_jurisdiction_code": "US_DE",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Corporation",
                        "bq_naics_sector_code": "42",
                        "bq_naics_sector_name": "Wholesale Trade",
                        "bq_revenue_mr": 2833862209.0,
                        "bq_company_address1_line_1": "12200 Herbert Wayne Ct Ste 150",
                        "bq_company_address1_city": "Huntersville",
                        "bq_company_address1_state": "NC",
                        "bq_company_address1_state_name": "North Carolina",
                        "bq_company_address1_county_fips": "37119",
                        "bq_company_address1_county_name": "Mecklenburg County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "28078",
                        "bq_company_address1_zip9": "28078-6397",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "Match-Mailable",
                        "bq_company_address1_rdi": "Commercial",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "16740",
                        "bq_company_address1_cbsa_name": "Charlotte-Concord-Gastonia, NC-SC",
                        "bq_company_address1_cbsa_type": "Metro",
                        "bq_company_address1_location": {
                            "lat": 35.38901,
                            "lng": -80.86884
                        }
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::275549425",
                    "relevance": 4.494479481310197,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::275549425",
                        "bq_company_name": "THE FRIEDKIN GROUP, INC.",
                        "bq_year_founded": "2010",
                        "bq_industry_name": "Motor Vehicle & Motor Vehicle Parts & Supplies",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Multi-entity U.S. organization",
                        "bq_sector_name": "Wholesale Trade",
                        "bq_naics_description": "Full-Service Restaurants",
                        "bq_company_ein": "275549425",
                        "bq_naics_code": "722511",
                        "bq_organization_jurisdiction_code": "US_TX",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Corporation",
                        "bq_naics_sector_code": "42",
                        "bq_naics_sector_name": "Wholesale Trade",
                        "bq_revenue_mr": 1833490307.0,
                        "bq_company_address1_line_1": "1375 Enclave Parkway Benefits Department",
                        "bq_company_address1_city": "Houston",
                        "bq_company_address1_state": "TX",
                        "bq_company_address1_state_name": "Texas",
                        "bq_company_address1_county_fips": "48201",
                        "bq_company_address1_county_name": "Harris County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "77077",
                        "bq_company_address1_zip9": "77077",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "No Match",
                        "bq_company_address1_rdi": "Unknown",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "26420",
                        "bq_company_address1_cbsa_name": "Houston-The Woodlands-Sugar Land, TX",
                        "bq_company_address1_cbsa_type": "Metro",
                        "bq_company_address1_location": {
                            "lat": 29.74889,
                            "lng": -95.61193
                        }
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::232078856",
                    "relevance": 4.494479481310197,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::232078856",
                        "bq_company_name": "DORMAN PRODUCTS INC",
                        "bq_year_founded": "1978",
                        "bq_industry_name": "Motor Vehicle & Motor Vehicle Parts & Supplies",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Multi-entity U.S. organization",
                        "bq_sector_name": "Wholesale Trade",
                        "bq_naics_description": "Other Miscellaneous Durable Goods Merchant Wholesalers",
                        "bq_company_ein": "232078856",
                        "bq_naics_code": "423990",
                        "bq_organization_jurisdiction_code": "US_PA",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Corporation",
                        "bq_naics_sector_code": "42",
                        "bq_naics_sector_name": "Wholesale Trade",
                        "bq_revenue_mr": 1733749000.0,
                        "bq_company_address1_line_1": "3400 E Walnut St",
                        "bq_company_address1_city": "Colmar",
                        "bq_company_address1_state": "PA",
                        "bq_company_address1_state_name": "Pennsylvania",
                        "bq_company_address1_county_fips": "42091",
                        "bq_company_address1_county_name": "Montgomery County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "18915",
                        "bq_company_address1_zip9": "18915-9768",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "Match-Mailable",
                        "bq_company_address1_rdi": "Commercial",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "37980",
                        "bq_company_address1_cbsa_name": "Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",
                        "bq_company_address1_cbsa_type": "Metro",
                        "bq_company_address1_location": {
                            "lat": 40.27402,
                            "lng": -75.24665
                        },
                        "bq_public_indicator": "true"
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::382252096",
                    "relevance": 4.494479481310197,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::382252096",
                        "bq_company_name": "FINISHMASTER, INC.",
                        "bq_year_founded": "1996",
                        "bq_industry_name": "Motor Vehicle & Motor Vehicle Parts & Supplies",
                        "bq_company_type": "Employer",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Corporation",
                        "bq_naics_sector_code": "42",
                        "bq_naics_sector_name": "Wholesale Trade",
                        "bq_revenue_mr": 653758038.0,
                        "bq_company_address1_line_1": "115 W Washington St Ste 700",
                        "bq_company_address1_city": "Indianapolis",
                        "bq_company_address1_state": "IN",
                        "bq_company_address1_state_name": "Indiana",
                        "bq_company_address1_county_fips": "18097",
                        "bq_company_address1_county_name": "Marion County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "46204",
                        "bq_company_address1_zip9": "46204-3761",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "Match-Mailable",
                        "bq_company_address1_rdi": "Commercial",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "26900",
                        "bq_company_address1_cbsa_name": "Indianapolis-Carmel-Anderson, IN",
                        "bq_company_address1_cbsa_type": "Metro",
                        "bq_company_address1_location": {
                            "lat": 39.76723,
                            "lng": -86.16086
                        }
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::208744739",
                    "relevance": 4.494479481310197,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::208744739",
                        "bq_company_name": "KAR AUCTION SERVICES INC",
                        "bq_year_founded": "2006",
                        "bq_industry_name": "Motor Vehicle & Motor Vehicle Parts & Supplies",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Multi-entity U.S. organization",
                        "bq_sector_name": "Wholesale Trade",
                        "bq_naics_description": "All Other Miscellaneous Store Retailers (except Tobacco Stores)",
                        "bq_company_ein": "208744739",
                        "bq_naics_code": "453998",
                        "bq_organization_jurisdiction_code": "US_DE",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Corporation",
                        "bq_naics_sector_code": "42",
                        "bq_naics_sector_name": "Wholesale Trade",
                        "bq_revenue_mr": 1519400000.0,
                        "bq_company_address1_line_1": "11299 Illinois St",
                        "bq_company_address1_city": "Carmel",
                        "bq_company_address1_state": "IN",
                        "bq_company_address1_state_name": "Indiana",
                        "bq_company_address1_county_fips": "18057",
                        "bq_company_address1_county_name": "Hamilton County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "46032",
                        "bq_company_address1_zip9": "46032-8887",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "Match-Mailable",
                        "bq_company_address1_rdi": "Commercial",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "26900",
                        "bq_company_address1_cbsa_name": "Indianapolis-Carmel-Anderson, IN",
                        "bq_company_address1_cbsa_type": "Metro",
                        "bq_company_address1_location": {
                            "lat": 39.97064,
                            "lng": -86.17054
                        },
                        "bq_public_indicator": "true"
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::362903176",
                    "relevance": 4.494479481310197,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::362903176",
                        "bq_company_name": "ROBERT BOSCH, LLC.",
                        "bq_year_founded": "1977",
                        "bq_industry_name": "Motor Vehicle & Motor Vehicle Parts & Supplies",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Multi-entity U.S. organization",
                        "bq_sector_name": "Wholesale Trade",
                        "bq_naics_description": "Offices of Lawyers",
                        "bq_company_ein": "362903176",
                        "bq_naics_code": "541110",
                        "bq_organization_jurisdiction_code": "US_DE",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Limited Liability Company",
                        "bq_naics_sector_code": "42",
                        "bq_naics_sector_name": "Wholesale Trade",
                        "bq_revenue_mr": 13985952706.0,
                        "bq_company_address1_line_1": "38000 Hills Tech Dr",
                        "bq_company_address1_city": "Farmington Hills",
                        "bq_company_address1_state": "MI",
                        "bq_company_address1_state_name": "Michigan",
                        "bq_company_address1_county_fips": "26125",
                        "bq_company_address1_county_name": "Oakland County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "48331",
                        "bq_company_address1_zip9": "48331-3418",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "Match-Mailable",
                        "bq_company_address1_rdi": "Commercial",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "19820",
                        "bq_company_address1_cbsa_name": "Detroit-Warren-Dearborn, MI",
                        "bq_company_address1_cbsa_type": "Metro",
                        "bq_company_address1_location": {
                            "lat": 42.49023,
                            "lng": -83.42575
                        }
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::222139469",
                    "relevance": 4.494479481310197,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::222139469",
                        "bq_company_name": "BMW OF NORTH AMERICA, LLC.",
                        "bq_year_founded": "1976",
                        "bq_industry_name": "Motor Vehicle & Motor Vehicle Parts & Supplies",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Multi-entity U.S. organization",
                        "bq_sector_name": "Wholesale Trade",
                        "bq_naics_description": "New Car Dealers",
                        "bq_company_ein": "222139469",
                        "bq_naics_code": "441110",
                        "bq_organization_jurisdiction_code": "US_DE",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Limited Liability Company",
                        "bq_naics_sector_code": "42",
                        "bq_naics_sector_name": "Wholesale Trade",
                        "bq_revenue_mr": 10612519302.0,
                        "bq_company_address1_line_1": "300 Chestnut Ridge Rd",
                        "bq_company_address1_city": "Woodcliff Lake",
                        "bq_company_address1_state": "NJ",
                        "bq_company_address1_state_name": "New Jersey",
                        "bq_company_address1_county_fips": "34003",
                        "bq_company_address1_county_name": "Bergen County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "07677",
                        "bq_company_address1_zip9": "07677-7739",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "Match-Mailable",
                        "bq_company_address1_rdi": "Commercial",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "35620",
                        "bq_company_address1_cbsa_name": "New York-Newark-Jersey City, NY-NJ-PA",
                        "bq_company_address1_cbsa_type": "Metro",
                        "bq_company_address1_location": {
                            "lat": 41.03878,
                            "lng": -74.07461
                        }
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::231693419",
                    "relevance": 4.494479481310197,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::231693419",
                        "bq_company_name": "SUBARU OF AMERICA, INC.",
                        "bq_year_founded": "1988",
                        "bq_industry_name": "Motor Vehicle & Motor Vehicle Parts & Supplies",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Multi-entity U.S. organization",
                        "bq_sector_name": "Wholesale Trade",
                        "bq_naics_description": "New Car Dealers",
                        "bq_company_ein": "231693419",
                        "bq_naics_code": "441110",
                        "bq_organization_jurisdiction_code": "US_DE",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Corporation",
                        "bq_naics_sector_code": "42",
                        "bq_naics_sector_name": "Wholesale Trade",
                        "bq_revenue_mr": 1481140973.0,
                        "bq_company_address1_line_1": "1 Subaru Dr",
                        "bq_company_address1_city": "Camden",
                        "bq_company_address1_state": "NJ",
                        "bq_company_address1_state_name": "New Jersey",
                        "bq_company_address1_county_fips": "34007",
                        "bq_company_address1_county_name": "Camden County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "08103",
                        "bq_company_address1_zip9": "08103-2204",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "Match-Mailable",
                        "bq_company_address1_rdi": "Commercial",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "37980",
                        "bq_company_address1_cbsa_name": "Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",
                        "bq_company_address1_cbsa_type": "Metro",
                        "bq_company_address1_location": {
                            "lat": 39.94289,
                            "lng": -75.10793
                        },
                        "bq_sf_active_employees_mr": "2"
                    }
                },
                {
                    "id": "id:bqcompany2:bqcompany2::812956513",
                    "relevance": 4.494479481310197,
                    "source": "bqcompany2_content",
                    "fields": {
                        "sddocname": "bqcompany2",
                        "documentid": "id:bqcompany2:bqcompany2::812956513",
                        "bq_company_name": "PAI HOLDCO, INC.",
                        "bq_industry_name": "Motor Vehicle & Motor Vehicle Parts & Supplies",
                        "bq_company_type": "Employer",
                        "bq_company_structure": "Single-entity organization",
                        "bq_sector_name": "Wholesale Trade",
                        "bq_naics_description": "Automobile and Other Motor Vehicle Merchant Wholesalers; Motor Vehicle Supplies and New Parts Merchant Wholesalers; Tire and Tube Merchant Wholesalers; Motor Vehicle Parts (Used) Merchant Wholesalers",
                        "bq_company_ein": "812956513",
                        "bq_naics_code": "423110; 423120; 423130; 423140",
                        "bq_company_isactive": "true",
                        "bq_company_lfo": "Corporation",
                        "bq_naics_sector_code": "42",
                        "bq_naics_sector_name": "Wholesale Trade",
                        "bq_revenue_mr": 2713338171.0,
                        "bq_company_address1_line_1": "3 Dakota Dr Ste 110",
                        "bq_company_address1_city": "New Hyde Park",
                        "bq_company_address1_state": "NY",
                        "bq_company_address1_state_name": "New York",
                        "bq_company_address1_county_fips": "36059",
                        "bq_company_address1_county_name": "Nassau County",
                        "bq_company_fgn_address1_cntry": "United States",
                        "bq_company_address1_zip5": "11042",
                        "bq_company_address1_zip9": "11042-1167",
                        "bq_company_address1_zip_type": "Standard",
                        "bq_company_address1_building_default_indicator": "No",
                        "bq_company_address1_summary": "Match-Mailable",
                        "bq_company_address1_rdi": "Commercial",
                        "bq_company_address1_dpv_match_code": "Yes",
                        "bq_company_address1_cbsa_code": "35620",
                        "bq_company_address1_cbsa_name": "New York-Newark-Jersey City, NY-NJ-PA",
                        "bq_company_address1_cbsa_type": "Metro",
                        "bq_company_address1_location": {
                            "lat": 40.76002,
                            "lng": -73.6894
                        }
                    }
                }
            ]
        }
    }
    ]

export default Dummy